name: Print Env Variable

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret
        run: |
          echo -e "$(cat /home/flag.txt)";
        shell: bash
